source "https://rubygems.org"

ruby "2.7.6"

gem "rails", "~> 7.1.5", ">= 7.1.5.1"

gem "puma", ">= 5.0"

gem "bcrypt", "~> 3.1.7"
gem "jwt"
gem "pundit"
gem "acts_as_list"

gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

gem "bootsnap", require: false

gem "rack-cors"

group :development, :test do
  gem "sqlite3", "~> 1.6.0"
  gem "dotenv-rails", groups: [:development, :test]

  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
end

group :production do
  gem 'pg', '~> 1.4.5'
end

group :development do
  gem "faker"
end

