source 'https://rubygems.org'

ruby '2.7.6'

# Core
gem 'bootsnap',                     require: false
gem 'puma',                         '>= 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.1.5', '>= 7.1.5.1'

# Authentication / Authorization
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'pundit'

# Utilities / Domain
gem 'acts_as_list'
gem 'tzinfo-data', platforms: %i[mswin mswin64 mingw x64_mingw jruby]

# Environment
gem 'dotenv-rails'

# Database
group :production do
  gem 'aws-sdk-core', '3.211', require: false
  gem 'aws-sdk-s3', '1.170', require: false
  gem 'pg', '~> 1.4.5'
end

group :development, :test do
  gem 'debug', platforms: %i[mri mswin mswin64 mingw x64_mingw]
  gem 'faker'
  gem 'sqlite3', '~> 1.6.0'
end

group :development do
  # add dev-only gems here
end
